### ISSUE TITLE
CSS live reload broken after this addon is installed

### ISSUE THREAD

**Issue by bgentry** [FortAwesome/ember-fontawesome#10]
After installing this addon, when I save any SCSS file in my repo (even with no changes), the entire app reloads. So CSS live reload is no longer working.

I created a repro here: https://github.com/bgentry/ember-css-hot-reload-demo

You can clone that, run `ember server`, and see that whenever you save `app.scss`, the entire page reloads. Get rid of the addon, and livereload works again.

**Comment by mlwilkerson** [comment]
Thanks, @bgentry, and sorry for the snag here. I'm looking into it.

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CSS live reload broken](https://trello.com/c/Fv23DWZM/19-css-live-reload-broken)

**Comment by bgentry** [comment]
@mlwilkerson no apology necessary, I knew what I was signing up for 🙂

**Comment by mlwilkerson** [comment]
And I'm very grateful that you signed up for it—helps us iterate and make it better for everyone, which I'm sure you can appreciate.

**Comment by bgentry** [comment]
Slightly more info: I've noticed that I can sometimes see the CSS livereload happen just a split second before the full page reload. So it's possible this issue is really "CSS changes trigger a full page reload". Hope that helps with debugging.

**Comment by mlwilkerson** [comment]
Thanks. Yeah, as I was looking at this earlier, it was unclear to me what the expected behavior is. Part of that is maybe that because it's such a small example app, the "full page reload" and "livereload only" cases are both very fast. If you could shed any further light on what you expect to see differently in the two cases, that would help.

Another thing I noticed (but I don't yet know whether it's relevant) is that you made the repro app with ember-cli 3.0. I haven't (yet) used ember-cli 3.0 for this add-on's development. Makes me wonder if anything is possibly different between those two. Do you have any thoughts there?

**Comment by bgentry** [comment]
The expected behavior is that the page itself does not get reloaded when CSS files are touched. That's only supposed to happen when JS or HBS files are changed. Normally if you make a CSS tweak, you'd expect the page to pretty quickly update in-place without re-rendering or losing any state.

A more obvious example app would render a component which updates its content a short time after it's first rendered.

Another way you can tell is if you enable "preserve log" in your Chrome network inspector, then you'll see that the `livereload` websocket request is restarted when the page reloads. That should not happen from CSS changes. You'd normally expect that one websocket request to stay open until JS/HBS changes occur/

I don't have any insight into whether this would be ember-cli 3.0 specific or not. Your best bet is probably to ask more about this in #ember-cli on Slack, I don't know enough about the build system to understand how/why this would be happening.

**Comment by bgentry** [comment]
I added a component to the repro app that just prints the current time when it is rendered. If livereload is working, you should never see that timestamp change when touching only CSS files.

**Comment by mlwilkerson** [comment]
OK, very helpful, thanks. I'm back to looking at this now.

**Comment by mlwilkerson** [comment]
@bgentry I just published `0.0.11-4` which I think fixes this issue. Could you give it a try and let me know if it does the trick for you?

The fix was, essentially, to just store some state that indicates that our our custom broccoli plugins had already built, and if so, then don't bother building again. So, they don't change the `vendorTree` and therefore the app doesn't need to reload.

This is based on some assumptions that I made, and I wonder what you think about these assumptions. We could take a different approach if need be.

Assumptions:
1. We only need to rebuild the tree-shaken icon packs (and auto loading of the library) if the build time configuration changes in `ember-cli.build.js`, which (I think) requires re-running `ember serve` or `ember build` anyway. So changing your fontawesome build time config would require a cold rebuild.
1. We only need to rebuild the FontAwesome stuff if something under `node_modules/@fortawesome` changes. In that case too, it's reasonable to do a cold rebuild: i.e. stop and re-start `ember serve`

So, the net effect is: if you want to rebuild the Font Awesome stuff after installing/removing npms or changing your `fontawesome` config in `ember-cli-build.js`, then you have to stop and restart `ember serve` or re-run `ember build`.

Does that seem reasonable?

**Comment by bgentry** [comment]
Just tried it out on my app and it looks like it fixed CSS livereload! I think it might have also lowered the incremental rebuild time which had gotten a lot worse after I switched addons. That would make sense if less work is being repeated every time. Thanks!

Assumption #1 sounds perfectly reasonable. Any time I make a change to `ember-cli-build.js` or `config/environment.js`, I expect to have to restart my app server.

AFAIK, assumption #2 would be different than other Ember addons. Typically updating a package while i.e. `ember serve` is running just rebuilds the required files from that package. I think it's reasonable for the addon to completely rebuild all its own resources in that scenario, but it shouldn't require the user to restart their ember process if that can be avoided.
