### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by donaldwasserman** [FortAwesome/ember-fontawesome#115]
**Describe the bug**
When using `ember auto import` and  this addon at `0.1.14`, I get this error: 

```
 - stack: TypeError: require(...) is not a function
    at getIcons (/Users/djwasserman/projects/nextrelease/NextRelease-Frontend/node_modules/@fortawesome/ember-fontawesome/lib/discover-configured-icons.js:31:37)
    at discoverConfiguredIcons (/Users/djwasserman/projects/nextrelease/NextRelease-Frontend/node_modules/@fortawesome/ember-fontawesome/lib/discover-configured-icons.js:11:17)
```

I'm not sure why require isn't working in this context and really don't understand why this is happening in my app specifically and not a more widely reported issue.

**Comment by st-h** [comment]
@donaldwasserman one reason that this is not a more widely reported issue might be that version `0.1.14` seems to be quite outdated as the current version is [`1.5.2`](https://www.npmjs.com/package/ember-auto-import). A simple `ember-auto-import` upgrade might resolve your issue. I have been using ember auto import along with this addon for quite a while and did not have any similar issues.

**Comment by donaldwasserman** [comment]
@st-h I edited a bit for clarity, but meant when upgrading _this addon_ from `0.1.10` to `0.1.14`

**Comment by st-h** [comment]
@donaldwasserman hmm, then I don't really have an idea right now what might be the cause. However, in certain situations a simple reboot or deleting cache folders might do wonders. Otherwise, a simple app to reproduce this, usually helps to clear things up a lot. 
Just checked, I am running latest versions of this add-on together with latest ember-auto-import and ember 3.12 without issues.

**Comment by donaldwasserman** [comment]
Well, I guess I'll close this right now, I suppose there's probably some other addon/babel setup misbehaving...
