### ISSUE TITLE
icon parameter needs to be explicitly stated {{fa-icon icon='coffee'}}

### ISSUE THREAD

**Issue by st-h** [FortAwesome/ember-fontawesome#16]
I have followed the instructions to install this addon, however quickly notificed that `{{fa-icon 'coffee'}}` only leads to a console message: `ember-console.js:24 Could not find icon undefined`.
After checking the source I found that the only way that currently seems to work is to explicitly provide the icon parameter to the component like `{{fa-icon icon='coffee'}}`. So either the docs or the addon currently seem to not work as intended.

**Comment by robmadole** [comment]
I'm not 100% sure of this but I think you have to explicitly list the icons you wish to use in `ember-cli-build.js`:

```
  let app = new EmberApp(defaults, {
    // Add options here
    fontawesome: {
      icons: {
        'fontawesome-free-solid': 'all'
      }
  })
```

@mlwilkerson is this correct?

**Comment by mlwilkerson** [comment]
Hi @st-h, could you quickly verify which version of the addon you have installed?

Because, "it works on my machine" :wink:

Positional parameter support was introduced in `0.0.11-2`.

And then yes, related to what @robmadole, you've got to make sure that you've configured your build to include some icons in order for them to be found. However, if it's finding them when you specify the `icon=` attribute, but not when you merely provide the icon as a positional parameter, then I don't think the problem is your build config. Most likely is that the addon needs to be updated. And if it's not that, then I may need further info to troubleshoot, since I can't reproduce it.

By the way, I just pushed a little update to the dummy app that shows examples (like you're using) of what's working in the latest release. (I haven't released this updated example in a new npm release—just pushed it to master so it's easy to see.) 
[See this line, in particular.](https://github.com/FortAwesome/ember-fontawesome/blob/ca803d840a5226778fd2dccdd666e828a4a0509b/tests/dummy/app/templates/application.hbs#L2)

**Comment by st-h** [comment]
@robmadole yes, I totally did it like that 😁 
@mlwilkerson this is interesting. I installed the addon today via `ember install` and it installed `0.0.10-1`. I even created a brand new app via `ember new` and then exactly followed the instruction here in the read me to install this add on. Just checked, but it installed `0.0.10-1` as well. Neither `yarn outdated` nor `npm outdated` did show that there is a newer version. However, if I manually update `package.json` to `0.0.11-2` it installs just fine and I can confirm that adding icons works as documented.
Just went back and took my clean dummy app and installed the addon again, and yet it installed `0.0.10-1` again.
and then... npmjs shows `0.0.10-1` as well: https://www.npmjs.com/package/@fortawesome/ember-fontawesome

**Comment by mlwilkerson** [comment]
OK, `0.0.11` is now the `latest`
