### ISSUE TITLE
coloring a percentage of an icon

### ISSUE THREAD

**Issue by st-h** [FortAwesome/ember-fontawesome#17]
I was able to use FA4 to create an upload progress indicator by using two overlays. One that is the background and a second colored one that is the growing progress. In the end it looked like that: 
![progress](https://i.imgur.com/Yr2Dp8H.png)
After switching to this addon I can no longer directly provide css style information to the element (the height of the colored element that should be visible). Power transform does not seem to offer a way to only display a fraction of an icon, does it? Is there a way to use this addon to display an icon which changes the amount it is colored in correspondence to a provided value?

**Comment by jrjohnson** [comment]
@st-h thanks for the report. It would be really helpful if you could attempt to do this with plain font awesome 5 and provide that code as a starting point. That makes it a bit easier to see where our API / components are going wrong.  If you did this in ember-font-awesome before providing that template code as well would be super helpful.

**Comment by st-h** [comment]
@jrjohnson sure. I created a [codepen](https://codepen.io/anon/pen/eVoELW) using FA4. I tried to use FA5, however setting a height did also change the width of the icon and I was not able to recreate the desired effect where the overlay is cropped and not resized. Maybe this issue would be a better fit at the fontawesome 5 repo, as by now this seems more like a general issue than an issue with the ember integration?

**Comment by robmadole** [comment]
Hey there @st-h. So this is not an issue with ember-fontawesome, so yeah we are going to close the issue here.

What you have actually works with Font Awesome 5 Web Fonts with CSS (https://use.fontawesome.com/releases/v5.0.8/css/all.css). I did a quick test with your codepen, replacing 4 with 5, and it worked out of the gate. So I don't think we have an issue with version 5 either.

What you may have ran into is that CSS designed to work with web fonts is not working with the newer SVG icons. I think the CSS would need to be reworked in order to handle this as the way the SVG implementation works is very different from web fonts.

If you still feel like we have an issue just file it in the main Font-Awesome repo and we'll take it from that context.

**Comment by st-h** [comment]
@robmadole thanks for the reply and checking. I had already opened an [issue](https://github.com/FortAwesome/Font-Awesome-Pro/issues/1037) in the main repo, however I thought the reference github provides would be sufficient. 
I found a way to make this work using the addons `safeStyle` property and the suggestion to clip via `clip: rect()` from the other issue. However, it would be great if we could do this using power transform.

**Comment by mlwilkerson** [comment]
@st-h I'm curious how you used `safeStyle` to reach your objective.
We just had a discussion recently about this:
https://github.com/FortAwesome/ember-fontawesome/pull/13#issuecomment-369114702

We currently _intentionally_ don't support binding to the _style_ of the `<svg>` for security reasons. The `safeStyle` is only there as a means of allowing us to bubble up some style from the `fontawesome` library (notably when doing a `transform`, such as a `rotate`—see the spinning magic example in the dummy app in the addon's repo). Our discussion was around how best to _inhibit_ developers from making use of that mechanism due to the security risks (XSS) involved in binding to a style attribute.

But...as we drew that line I did wonder when we'd find a use case that would drive us to figure out a reasonable way to allow developers to bind to the style of the `<svg>`. Maybe we've found just such a use case here.

**Comment by st-h** [comment]
@mlwilkerson well, interesting...

here is the relevant code for the clipped icon: 
component.hbs:
```
  {{fa-icon 'arrow-circle-up' prefix='fas' class='incomplete' safeStyle=progressStyle}}
```
component.js:
```
  progressStyle: computed('uploadManager.progress', function() {
    return htmlSafe('clip: rect(0, 1em, ' +  (1 - progress) + 'em, 0);');
  })
```

this produces following html:
```
<svg style="clip: rect(0, 1em, 0.647em, 0);" ...........etc
```

I don't really think this is a use case to provide a way to specify style information. I only need to do that because we don't have support in power transform to either
- clip an icon
- color a portion of an icon

Given that most likely the first feature will fit a lot more use cases, be way easier to implement and will enable users to build the second feature cleanly, I propose to add a clip operation to power transform. Just think about that very long half-star discussion, which could have been totally avoided by such a power transform. Just let us clip and people will be able to create colored quarter stars and whatever and what not.

However, in case you decide to add a style property to the component: I think you should be able to check if the provided value is htmlSafe and throw an exception or log a warning if not. Ember is doing something like that since quite some time.

**Comment by st-h** [comment]
As of recent ember versions, workarounds to this issue are now officially deprecated. Any ideas how to tackle this, as there has not been any progress or a response from the team over at the main repo for over a year?

**Comment by mlwilkerson** [comment]
Sorry, @st-h. I don't know of a workaround to recommend. I've re-read all of this and the linked issues, getting re-acquainted with the concern. I appreciate your persistence. I don't yet know whether adding the crop feature (or any similar feature) as you've requested is going to be a workable solution for us. But I do intend to have this in mind as we prioritize future work. I'm sorry I can't offer any solutions at this time.
