### ISSUE TITLE
Icon sizes changed after upgrading

### ISSUE THREAD

**Issue by gzurbach** [FortAwesome/ember-fontawesome#196]
**Describe the bug**
After upgrading to `0.3.0` I noticed that the size of some icons changed. For instance, `ellipsis-v` is displayed much smaller than expected, and `angle-down`/`angle-up` also look smaller.

**Reproducible test case**
Upgrade to 0.3.0 then use `<FaIcon @icon="sliders-h" />`.

**Expected behavior**
I ran a diff between the icons rendered in `0.2.3` and `0.3.0`:
<img width="1085" alt="Screen Shot 2022-01-24 at 5 14 35 PM" src="https://user-images.githubusercontent.com/795927/150821143-35c28f0a-89ef-4b28-891b-703372ce9ddb.png">
The lack of ID and ember-view class is expected with Octane, but the viewBox should be identical.

**Desktop**
 - Browser Chrome
 - Version 97

I hope there was enough helpful information? What's weird is that it's only happening with a few icons 🤔

**Comment by jrjohnson** [comment]
Thanks for the report @gzurbach! I'm surprised as well that this is only happening with some icons. I'll try and find some time to debug this during the upcomming week, but I may not get to it for a bit so any help from everyone else would be very welcome here in tracking this down and fixing it.

**Comment by st-h** [comment]
@gzurbach thanks for opening this. I was wondering why I was unable to center my icons, even though it seemed to work flawlessly in the past. With 0.3.0 the icon seemed to be overflowing. Turns out the incorrect viewBox is the culprit here as well.

0.2.2: 
![Screenshot 2022-01-24 at 19 52 15](https://user-images.githubusercontent.com/5768353/150846305-274394cb-05ad-474b-978f-09074ee5c0ce.png)

0.3.0:
![Screenshot 2022-01-24 at 19 55 30](https://user-images.githubusercontent.com/5768353/150846360-ba8a7119-a184-4d72-915f-db53ec89e444.png)

**Comment by st-h** [comment]
There you go. Looks good to me when checking the dummy app. 

Unfortunately I was unable to `yarn link` the addon because it resulted I weird build error. So I could not test if everything is fixed within my app.

```
Build Error (broccoli-fontawesome-pack: pro-solid-svg-icons)

Cannot find module '@fortawesome/pro-solid-svg-icons'
Require stack:
- ember-fontawesome/vendor/broccoli-fontawesome-pack.js
- ember-fontawesome/index.js
```

I also was unable to test the icon where I was noticing the issue because it is not included in the free font awesome package and I didn't want to go through all the mumbo jumbo to make the paid icons work with the dummy app. 

And lastly (off topic): I do hate the icons.js file. What's even worse is that editing it takes a whole rebuilt of the app during development.

Now, can we get a release please.

**Comment by jrjohnson** [comment]
Thanks @st-h for tracking this down. I merged your PR and I've request a release from the Fortawesome team. 

Aside: I also hate the `icons.js` file, but haven't come up with anything better. I'm very much hoping that once RFC 779 lands with first class imports in template we can do away with most of the build tooling here and just import directly from `node_modules` for any icon. Since this solves so many problems I'm not terribly worried about making a better intern solution here. I'm happy to merge stuff though if there are improvements you can see.

**Comment by gzurbach** [comment]
Wow thanks for the quick turnaround everyone! 👏
