### ISSUE TITLE
tagName span

### ISSUE THREAD

**Issue by mhluska** [FortAwesome/ember-fontawesome#4]
I'm trying to migrate to this from simply dropping in the `fontawesome-all.js` script and everything is working fine except for one difference: the `fa-icon` components seem to have `<span>` tag wrapping the `<svg>` tag whereas in the previous version, svg was the top level element.

Also it looks like you're using some svg-related `attributeBindings` for the span element.

**Comment by mlwilkerson** [comment]
@mhluska great timing :-) I've actually been in the process of correcting those very things and pushing the updates to the `component-refactor` branch. Could you give that a try and let me know how that works?

**Comment by mhluska** [comment]
Ok I'll try now. Thanks :)

**Comment by mlwilkerson** [comment]
or, I could cut another pre-release version and push it to NPM.

There are a couple more tweaks I need to make before merging it all into `master`

**Comment by mhluska** [comment]
That would work too.

**Comment by mlwilkerson** [comment]
OK, try `@fortawesome/ember-fontawesome@0.0.11-1`

**Comment by mlwilkerson** [comment]
And if you know how to properly handle the CSS escaping for `style` binding, that's one of the other things that needs fixing at the moment.

**Comment by mhluska** [comment]
With this new version, is there way to pass a class to the svg component? I have a bunch of `class='...'` on the icon components which won't work now not surprisingly:

```
Assertion Failed: You cannot use `classNameBindings` on a tag-less component:
```

**Comment by mlwilkerson** [comment]
By the way, something I hadn't realized was still happening in the `0.0.10-1` prerelease is that our mutation observer was enabled. That was messing things up for me in my initial attempts at these latest changes. So in `0.0.11-1` I've added a config change to the `<head>` that disables `autoReplaceSvg` and `observeMutations` in the `FontAwesomeConfig` (this will be the default in our next minor release of FA). In the meantime, I'll be curious to know whether your code happened to be relying on those automagical things happening—since they'll be turned off in `0.0.11-1`.

**Comment by mlwilkerson** [comment]
Hmmm...I might have thought that class thing would work. I'll try it in the dummy app, but could you provide an example of what you're doing that is not working?

**Comment by mhluska** [comment]
Disregard the class thing. That was a different issue on my end. Everything seems to be working perfectly on my end now.

**Comment by mhluska** [comment]
Thanks again for your help.

**Comment by mlwilkerson** [comment]
Cool, cause I just tried it and "it worked on my machine" ;-)
